### ISSUE TITLE
[documentation] Поправить орфографию в requests.md

### ISSUE THREAD

**Issue by Sergey-Shabanov** [russsiq/laravel-docs-8.x-ru#2]
###  Описание

В некоторых словах документа [HTTP-запросы](https://github.com/russsiq/laravel-docs-8.x-ru/blob/main/docs/requests.md) имеются окончания, которые по всей видимости, необходимо поправить.
Ниже приведены фрагменты и ссылки на строки документа.

#### Пруфы

`которые содержат массив входных данные` -> **данных**
 [requests.md#L235](https://github.com/russsiq/laravel-docs-8.x-ru/blame/main/docs/requests.md#L235)

`...одно из ваших настроенных [файловый хранилищ](filesystem.md) `-> **файловых** хранилищ
[requests.md#L446](https://github.com/russsiq/laravel-docs-8.x-ru/blame/main/docs/requests.md#L446)

**Comment by russsiq** [comment]
Для подобных мелких ошибок, думаю, что лучше сразу [запрос отправлять](https://github.com/russsiq/laravel-docs-8.x-ru/pulls).

**Comment by Sergey-Shabanov** [comment]
Я где-то читал, что на основе тикетов можно ветки создавать, коммитить в них, а затем в пулреквесте упоминать номер тикета с определенным тегом, и он какбэ автоматом будет закрываться 👍 
Хочу попробовать этот кейс.

К тому же добавление тикета происходит в процессе чтения документации, что-то вроде памятки, чтобы не забыть. А уже само исправление когда под рукой IDE. Мне кажется это естественным потоком активности.

При молчаливых коммитах и последующим пулреквесте есть вероятность обработать одну и ту же проблему одновременно, и посвятить этому лучшие годы своей жизни 😄 

Так всё таки ISSUE или PULL REQUEST ?

**Comment by russsiq** [comment]
PULL REQUEST - для мелких правок, которые не нужно обсуждать и есть большая вероятность, что запрос будет принят. Кучу коммитов не надо накапливать – мелкая правка в одном файле, быстрый коммит.

ISSUE - если вы собираетесь что-то объемное сделать, то просто оповестите об этом, чтобы можно было обсудить.

-----

А так-то тренируйтесь, я не против.

**Comment by Sergey-Shabanov** [comment]
ОК, понял
