### ISSUE TITLE
Документация

### ISSUE THREAD

**Issue by Butochnikov** [russsiq/laravel-docs-8.x-ru#4]
Привет. Я дебил.

**Comment by russsiq** [comment]
Привет.

1. Чтобы разобраться в самом фреймворке.
1. Потому что там некоторый застой организовался.
1. Ну и хотелось бы называть Gates шлюзами и тому подобные мелочи.

**Comment by jhaoda** [comment]
@russsiq так сообщество не мешает разбираться во фреймворке и не требует называть гейты сторого гейтами или как там. А застой организовался как раз потому, что некому было поднять упавший флаг переводчечской деятельности.

**Comment by russsiq** [comment]
@jhaoda, вы правы. Что сделано, то сделано, извините.

**Comment by jhaoda** [comment]
@russsiq так никто не мешает сейчас сделать переезд в сообщество. Конечно, если вы в принципе не против.

**Comment by russsiq** [comment]
@jhaoda, мне это не надо. Да и сообществу, это тоже не надо: начать называть сервис-контейнер – контейнером служб, а провайдеры – поставщиками.

**Comment by russsiq** [comment]
Это типичный репозиторий с лицензией [MIT](https://github.com/russsiq/laravel-docs-8.x-ru#license).

**Comment by Butochnikov** [comment]
@russsiq спасибо за ответ и перевод.

**Comment by russsiq** [comment]
@Butochnikov, пожалуйста.

**Comment by russsiq** [comment]
Ввиду того, что на данном сайте rularavel[dot]com размещена документация вашего сообщества для Laravel версии 6.x, и в связи с тем, что администратор форума утверждает `Русская документация доступна здесь: ... переводиться нами в свободное время`, отмечу, что никакого отношения к тому сайту и их владельцам не имею.

**Comment by russsiq** [comment]
@Butochnikov, привет. А чем вам не угодил домен laravel[dot]ru, что вы создали laravel.su?

**Comment by russsiq** [comment]
@jhaoda , @Butochnikov – вы зашли на частный репо, какую-то чушь спросили и друг друга наплюсовали. Вам так нормально живется? Вы же получили ответ? А когда вас спрашивают вы язык в жопу втыкаете?

**Comment by russsiq** [comment]
Ответ один – они не мужики, чтобы ответить. Лучше поудалять вопросы и заблокировать – это жид, самый яркий представитель хабра и стека.

**Comment by russsiq** [comment]
@jhaoda , @Butochnikov Ответ один – вы не мужики, чтобы ответить. Лучше поудалять вопросы и заблокировать – это жид, самый яркий представитель хабра и стека.

**Comment by SerafimArts** [comment]
@russsiq заблокировал тебя я, как раз за подобные высказывания. Если будут какие-либо технические вопросы - можешь написать мне на почту.

**Comment by russsiq** [comment]
@SerafimArts , это хорошо, что у этих "псин" есть хозяин, который скомандует в будущем, чтобы они не заходили на частный репо, и не диктовали свои условия, о том, что я и где должен опублтковывать.

**Comment by russsiq** [comment]
@Sergey-Shabanov , еще есть вопросы?

**Comment by russsiq** [comment]
@SerafimArts, я даже вам буду благодарен, что бы вы эту "дичь" держали при себе: в хабре или стекO или откуда вы.

Дай бог, чтобы в рамках СНГ, наконец-то, появилось во истину общество программистов!

**Comment by russsiq** [comment]
Дрочите лесом, что хабр, что со https://www.youtube.com/watch?v=gjHn5Ia__hM

**Comment by russsiq** [comment]
@Butochnikov , нужно смириться и жить дальше.
