### ISSUE TITLE
Актуализация перевода

### ISSUE THREAD

**Issue by slider23** [russsiq/laravel-docs-8.x-ru#7]
Приветствую.

Ребят, вы имеете отношение к сайту rularavel.com ? Я общался с ними, думая, что этот перевод их, затем увидел вашу репу.

Я разместил ваш перевод на laravel.su, интегрировав его в нашу систему поддержания актуальности перевода. Мы пишем в начале каждого файла коммит оригинальной доки, с которого делался перевод, и дальше допереводим только новые куски, делая diff по оригинальной доке. 
Вот инструкция, по которой мы работаем: https://laravel.su/articles/rus-documentation-contribution-guide
Вот страница статуса переводов: https://laravel.su/status/8.x

Как вы смотрите на то, чтобы дальше переводить в репе https://github.com/LaravelRUS/docs , опираясь на нашу методику ?

**Comment by slider23** [comment]
UPD почитал закрытый issue, от нас уже обращались )
Если хотите, можете переводить у себя в репе, но рекомендую перейти на нашу систему поддержки актуальности, иначе закопаетесь со временем.

**Comment by russsiq** [comment]
Привет.

Нет, не имею никаких отношений с тематическими сайтами / сообществами. Так же нет в планах куда-то вливаться.

Это просто частный репо с лицензией MIT.

Единственная просьба – не делайте ссылок на этот репо с вашего сайта laravel.su.

Хотя, еще – подправьте содержание, там ошибки `Компеляция ресурсов`

**Comment by russsiq** [comment]
Содержание там вообще странное: не соответствует названиям разделов в документации.

Например, `Промежуточное ПО` и [`Посредники`](https://laravel.su/docs/8.x/middleware)

**Comment by slider23** [comment]
Спасибо, понял вашу позицию.
Оглавление проверю, оно там действительно из другого места.

**Comment by russsiq** [comment]
@slider23, привет.

Посмотрев коммиты в репо вашего "сообщества", пришел к выводу, что вы являетесь двигателем перевода документации в данный момент. Это так?

**Comment by slider23** [comment]
Да, в последнее время с ней возился почти только я, да и то по остаточному принципу, когда было время.
По-моему особой необходимости в переведённой документации сейчас уже нет, учитывая разнообразие учебных материалов. Оригинальная документация в целом написана понятно, можно даже текст не читать, смотреть только код.

**Comment by russsiq** [comment]
Вы далеко не правы. Я этот перевод начинал для себя, даже не планировал все переводить. Сейчас, когда кодируешь, даже не смотря на IDE захожу на документацию по валидации, тестам и т.д. Изначально как планировал, так и пользуюсь. Взять даже пример еще о параллельном тестировании: переводя доку узнал, что есть такое, иногда приятно параллельно).

Остались непереведенные только пакеты, которые мне не интересны. Но есть джетсрим, который мне интересен БЫ был, но уже не так. Вот вы как двигатель перевода стали бы уделять этой технологии время?

**Comment by russsiq** [comment]
Я такой человек, который даже зная, о какой-либо функции PHP, например, `explode` – все равно открою браузер и вобью ее в строку, пролистаю до фрагмента, где описано, что эта функция возвращает, потом пролистаю, что она принимает, потом перещелкну на английский язык, потом примеры посмотрю... Именно по этому мне нравится документация Laravel на русском.

**Comment by russsiq** [comment]
Ладно, всю эту панику, истерику ))) Джетстрим и иже с ним нужно переводить?

**Comment by slider23** [comment]
В телеграм-чатах периодически появляются новички, которые не умеют читать по-английски и ищут русскую документации. Если есть время и желание, можно перевести.
Для России только неактуально всё, связанное с биллингом - Stripe у нас не работает.

**Comment by russsiq** [comment]
Ясно.

**Comment by russsiq** [comment]
@slider23, сам-то где работаешь?

**Comment by russsiq** [comment]
@slider23, не трать свое время на всякие "безобразные" сообщества. Я был в стекру, моими ответами зачитывались. Вытаскивай себя с сообществ.

**Comment by slider23** [comment]
Я на себя работаю. )
Ты в Телеграме есть, может, там лучше продолжить ? Я там @sequeller

**Comment by russsiq** [comment]
Я в этом плане асоциальный, даже без телефона живу. Безработный. Забей ты на эти сраные сообщества. https://www.youtube.com/watch?v=CclvFMDCI7o

**Comment by russsiq** [comment]
@slider23 нет никаких сообществ, не тревож свой мозг

**Comment by russsiq** [comment]
Дебилы одни кругом, типа [жедая](https://github.com/jhaodal)

**Comment by russsiq** [comment]
Давно уже написано про ваше ,,,, сообщество https://cleverman.org/post/tvoy-kod-govno-ne-ishodite-na-govno-pro-laravel-ru-soobshchestvo, и не мною. И про SO, в котором я был – гуляйте лесом. 

От вас убегаешь, а вы догоняете.

**Comment by slider23** [comment]
Да, токсичность некоторых людей в комьюнити - это старая проблема. Поэтому ни в группе вк, ни в телеграм-чате, ни в дискорд-группе меня нет ) "В сообществе" я только тут, на гитхабе, доку перевожу. Иногда.

**Comment by russsiq** [comment]
@slider23, я когда увидел у себя этот ник жида, в шоке был

**Comment by russsiq** [comment]
Если он такой грамотный, пусть тебя на работу возьмет.

**Comment by russsiq** [comment]
@jhaoda вы где работаете?

**Comment by russsiq** [comment]
https://www.youtube.com/watch?v=QtkuqGkxp0M

**Comment by russsiq** [comment]
@slider23, не слушай их.
